"""fix

Revision ID: 3d002a646b8a
Revises: 5ca042180835
Create Date: 2025-02-18 15:40:45.611703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d002a646b8a'
down_revision: Union[str, None] = '5ca042180835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sfs1_products_productId', table_name='products')
    op.drop_table('products')
    op.drop_index('email', table_name='users')
    op.drop_index('ix_sfs1_users_userId', table_name='users')
    op.drop_index('password', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=6), nullable=True),
    sa.Column('isVerified', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=True),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pic', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updatedAt', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('password', 'users', ['password'], unique=True)
    op.create_index('ix_sfs1_users_userId', 'users', ['userId'], unique=False)
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_table('products',
    sa.Column('productId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('desc', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('pricePlan', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('thumbnail', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updatedAt', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('productId'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sfs1_products_productId', 'products', ['productId'], unique=False)
    # ### end Alembic commands ###
