"""Product Table

Revision ID: cb78fa79effd
Revises: 46c23db1901a
Create Date: 2025-02-11 09:09:40.033001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb78fa79effd'
down_revision: Union[str, None] = '46c23db1901a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    op.drop_index('ix_sfs1_users_userId', table_name='users')
    op.drop_index('password', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=6), nullable=True),
    sa.Column('isVerified', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=True),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pic', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updatedAt', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('password', 'users', ['password'], unique=True)
    op.create_index('ix_sfs1_users_userId', 'users', ['userId'], unique=False)
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
