"""Create User Model

Revision ID: f6c46e1c9b68
Revises: 
Create Date: 2024-12-13 02:40:29.498504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6c46e1c9b68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('email', table_name='users')
    #op.drop_table('users')
    #op.drop_index('userIdx', table_name='usertokens')
    #op.drop_table('usertokens')
    #op.drop_index('name', table_name='posts')
    #op.drop_index('userIdx', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('postId', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('desc', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('thumbnail', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name='postByUser', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('postId'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('userIdx', 'posts', ['userId'], unique=False)
    op.create_index('name', 'posts', ['name'], unique=True)
    op.create_table('usertokens',
    sa.Column('userId', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('browserId', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=False),
    sa.Column('tokenValue', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('expiresAt', mysql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name='tokenforUser', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'browserId'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('userIdx', 'usertokens', ['userId'], unique=False)
    op.create_table('users',
    sa.Column('userId', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False),
    sa.Column('firstName', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('lastName', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pic', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=6), nullable=True),
    sa.Column('isVerified', mysql.CHAR(collation='utf8mb4_unicode_ci', length=1), server_default=sa.text("'F'"), nullable=True),
    sa.Column('role', mysql.CHAR(collation='utf8mb4_unicode_ci', length=5), server_default=sa.text("'user'"), nullable=True),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
